config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :dogs, to: 'pets#dogs', only: [:index]
  resources :cats, to: 'pets#cats', only: [:index]

  resources :pets, only: [:index, :show] do
    collection do
      get :random, to: 'pets#random'
    end
  end

  # Admin routes, no traffic goes here, but there are some slow queries
  namespace :admin, layout: 'admin' do
    root to: redirect('/admin/pets')
    resources :pets, only: [:index]
  end

  # PgHero routes, use them to figure out long running queries
  mount PgHero::Engine, at: "pghero"

  # Mock routes, use them to simulate slow services
  namespace :mock do
    get '/slow-service', to: '/mock#slow_service'
    get '/outlier/:id', to: '/mock#outlier'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  geocoded_by :address

  belongs_to :shelter
  has_many :adoption_applications
  has_many :pet_vaccinations
  has_many :vaccinations, through: :pet_vaccinations
  has_many_attached :photos
  has_many :pet_views

  default_scope { available.recent }

  scope :most_viewed, -> do
    joins('LEFT JOIN (SELECT pet_id, COUNT(*) as pet_count FROM pet_views GROUP BY pet_id) pet_counts ON pet_counts.pet_id = pets.id')
      .reorder(Arel.sql('COALESCE(pet_count, 0) DESC, pets.created_at DESC'))
  end

  scope :recent, -> { order("created_at DESC") }
  scope :available, -> { where(adoption_date: nil) }
  scope :random, -> { order("RANDOM()") }
  scope :search, ->(search) { where("name ILIKE :search OR breed ILIKE :search", { search: "%#{search}%" }) }

  scope :dogs, -> { where(pet_type: "dog") }
  scope :cats, -> { where(pet_type: "cat") }
  scope :by_city, ->(city_name, distance) do
    city = BIGGEST_CITIES.find { |city| city[:name] == city_name }
    return none unless city
    near([city[:latitude], city[:longitude]], distance, unit: :km)
  end

  enum pet_type: { dog: 0, cat: 1 }
  enum gender: { male: 0, female: 1, unknown: 2 }
  enum size: { small: 0, medium: 1, large: 2, extra_large: 3 }

  validates :name, presence: true
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :breed, presence: true
  validates :color, presence: true
  validates :weight, numericality: { greater_than: 0 }

  def image_url(width: 100, height: 100)
    if dog?
      "https://placedog.net/#{width}/#{height}?id=#{(id || 0) % 230}"
    else
      "https://placekitten.com/#{width}/#{height}?image=#{(id || 0) % 16}"
    end
  end

  def similar_type_pets
    Pet.where.not(id: id).where(pet_type: pet_type).random
  end

  def similiar_name_pets
    first_name = name.split(" ").first
    last_name = name.split(" ").last
    Pet.where.not(id: id).where("name ILIKE ?", "%#{last_name}%").or(
      Pet.where.not(id: id).where("name ILIKE ?", "%#{first_name}%")
    ).random
  end

  def tagline
    if dog?
      "#{name} is a #{age} year old #{breed} looking for a home!"
    else
      JSON.parse(Net::HTTP.get(URI("https://catfact.ninja/fact")))["fact"]
    end
  end

  def promo
    if dog?
      Net::HTTP.get(URI("http://localhost:#{ENV["RAILS_PORT"]}/mock/slow-service"))
    else
      Net::HTTP.get(URI("http://localhost:#{ENV["RAILS_PORT"]}/mock/outlier/#{id}"))
    end
  end

  def dog?
    pet_type == "dog"
  end
end

app/models/pet_vaccination.rb
class PetVaccination < ApplicationRecord
  belongs_to :pet
  belongs_to :vaccination
end

app/models/pet_view.rb
class PetView < ApplicationRecord
  belongs_to :pet
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  geocoded_by :address

  has_many :pets

  validates :name, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  has_many :pet_vaccinations
  has_many :pets, through: :pet_vaccinations

  validates :name, presence: true
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    @total_shelters = Shelter.count
    @top_shelters = Shelter.top_5

    @total_pets = Pet.count
    @total_dogs = Pet.dogs.count
    @total_cats = Pet.cats.count

    @adopted_last_week = Pet.where("adoption_date > ?", 1.week.ago).count
    @adopted_last_month = Pet.where("adoption_date > ?", 1.month.ago).count
    @adopted_last_year = Pet.where("adoption_date > ?", 1.year.ago).count

    @total_applications = AdoptionApplication.count
    @total_applications_last_week = AdoptionApplication.where(created_at: 1.week.ago..).count
    @total_applications_last_month = AdoptionApplication.where(created_at: 1.month.ago..).count
    @total_applications_last_year = AdoptionApplication.where(created_at: 1.year.ago..).count
  end
end

app/controllers/admin/pets_controller.rb
class Admin::PetsController < ApplicationController
  layout 'admin'
  def index
    @pets = Pet.all
    @pets_total_count = @pets.count
    @pets = @pets.page(params[:page]).per((params[:per_page] || 100).to_i)
  end
end

app/controllers/admin/shelters_controller.rb
class Admin::SheltersController < ApplicationController
end

app/controllers/admin/vaccinations_controller.rb
class Admin::VaccinationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    list_size = 4

    @pets = {
      recently_added: Pet.recent.limit(list_size),
      recently_adopted: Pet.all.order(adoption_date: :desc).limit(list_size),
      random: Pet.random.limit(list_size),
      most_viewed: Pet.all.most_viewed.limit(list_size),
    }
  end
end

app/controllers/mock_controller.rb
class MockController < ApplicationController
  def slow_service
    sleep(0.5)
    render plain: "This is a cool pet you might like!"
  end

  def outlier
    if slow_down?
      sleep(1)
      render plain: "This is a REALLY cool pet you might like!"
    else
      render plain: "This is a cool pet you might like!"
    end
  end

  private

  def slow_down?
    params[:id].to_i % 100 == 0
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @filter = params[:filter]
    @search = params[:q].presence
    @pets = filtered_pets
    @pets = @pets.search(@search) if @search.present?
    @pets_count = @pets.count
    @pets = @pets.page(params[:page]).per(9)
    respond_to do |format|

      format.html { render :index }
      format.json do
        render json: {
          pets: @pets.map { |pet| { id: pet.id, name: pet.name, link: pet_path(pet), breed: pet.breed } },
          matching_pets_count: @pets_count
        }
      end
    end
  end

  def dogs
    @filter = 'dogs'
    @pets = filtered_pets.page(params[:page]).per(9)
    @pets = @pets.by_city(params[:distance_from], params[:distance].to_i) if params[:distance_from].present?
    @search_form = {
      distance_from: params[:distance_from],
      distance: params[:distance],
    }
    @pets_count = @pets.total_count
  end

  def cats
    @filter = 'cats'
    @pets = filtered_pets.page(params[:page]).per(9)
    @pets = @pets.by_city(params[:distance_from], params[:distance].to_i) if params[:distance_from].present?
    @search_form = {
      distance_from: params[:distance_from],
      distance: params[:distance],
    }
    @pets_count = @pets.total_count
  end

  def random
    @pet = Pet.random.first
    redirect_to pet_path(@pet)
  end

  def show
    @pet = Pet.find(params[:id])
    @extra_info =
    PetView.create(pet_id: @pet.id)
  end

  private

  def filtered_pets
    case @filter
    when "dogs"
      @pets = Pet.dogs
    when "cats"
      @pets = Pet.cats
    when "most_viewed"
      @pets = Pet.most_viewed
    when "recent"
      @pets = Pet.recent
    else
      @pets = Pet.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(current_path = nil)
    @page_subtitle ||= current_path&.split("/")&.first&.titleize
    [I18n.t("application.title"), @page_subtitle].flatten.compact.join(" - ")
  end
end

app/views/admin/pets/index.html.erb
<div class="container-fluid">

  <div class="col-md-12">
    <center>
      <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
    </center>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h2>Admin::Pets (<%= @pets_total_count %>)</h2>
    </div>
    <div class="col-md-12">
      <table class="table table-responsive">
        <thead>
        <tr>
          <th>Type</th>
          <th>Name</th>
          <th>Shelter name</th>
          <th>Age</th>
          <th>Breed</th>
          <th>Vaccinations</th>
          <th>Views</th>
        </tr>
        </thead>
        <tbody>
        <% @pets.each do |pet| %>
          <tr>
            <td>
              <% if pet.pet_type == 'dog' %>
                <i class="fa fa-dog" style="color: red"></i>
              <% else %>
                <i class="fa fa-cat" style="color: blue"></i>
              <% end %>
            </td>
            <td><%= pet.name %></td>
            <td><%= pet.shelter.name %></td>
            <td><%= pet.age %></td>
            <td><%= pet.breed %></td>
            <td><%= pet.vaccinations.map(&:name).join(', ') %></td>
            <td><%= pet.pet_views.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>


    <div class="col-md-12">
      <center>
        <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
      </center>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <h1><%= I18n.t('application.title') %></h1>
        <p><%= I18n.t('application.description') %></p>
      </div>
    </div>
  </div>
  <% @pets.each do |filter, pets| %>
    <%= render 'pets/pets_list', pets: pets, filter: filter %>
  <% end %>
</div>

app/views/layouts/_admin_navigation.html.erb
<nav class="navbar navbar-inverse" style="border-radius: 0px">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#main-navbar" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <img src="/favicon.png" style="display: inline-block; height: 25px; padding: 3px">
        <%= I18n.t('application.short_title') %>
      </a>
    </div>
    <div id="main-navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">Homepage</a></li>
        <li><a href="<%= admin_pets_path %>">Admin::Pets</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse" style="border-radius: 0px">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#main-navbar" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <img src="/favicon.png" style="display: inline-block; height: 25px; padding: 3px">
        <%= I18n.t('application.short_title') %>
      </a>
    </div>
    <div id="main-navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">
          <i class="fa fa-house"></i>
          Homepage
        </a></li>
        <li><a href="<%= dogs_path %>" title="<%= Pet.dogs.count %> dogs waiting to be adopted!">
          <i class="fa fa-dog"></i>
          Dogs
        </a></li>
        <li><a href="<%= cats_path %>" title="<%= Pet.cats.count %> cats waiting to be adopted!">
          <i class="fa fa-cat"></i>
          Cats
        </a></li>
        <li><a href="<%= pets_path(filter: 'recent') %>">
          <i class="fa fa-clock"></i>
          Recent
        </a></li>
        <li><a href="<%= pets_path(filter: 'most_viewed') %>">
          <i class="fa fa-eye"></i>
          Most Viewed
        </a></li>
        <li><a href="<%= random_pets_path %>">
          <i class="fa fa-random"></i>
          Random
        </a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= form_with url: pets_path, method: :get, local: true, class: 'navbar-form navbar-right' do |f| %>
            <%= f.text_field :q, placeholder: "search pet name", value: params[:q], class: "form-control", id: 'searchbox', autocomplete: "off" %>
            <ul id="search-results" class="dropdown-menu" aria-labelledby="dropdownMenu1" style="margin-right: 70px"></ul>
            <button class="btn btn-default" type="submit">Search</button>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <title>Admin</title>
  <link rel="apple-touch-icon-precomposed" href="/favicon.png">
  <link rel="icon" href="/favicon.png" sizes="128x128" type="image/png">
  <meta name="language" content="<%= I18n.locale %>">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta charset="utf-8">
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css", media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
<%= render 'layouts/admin_navigation' %>
<% if flash.present? %>
  <div class="row">
    <div class="col-md-12">
      <%= flash_messages %>
    </div>
  </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= page_title %></title>
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="/favicon.png">
    <link rel="icon" href="/favicon.png" sizes="128x128" type="image/png">
    <link rel="icon" href="/favicon.ico" sizes="any" type="image/svg+xml">
    <meta name="language" content="<%= I18n.locale %>">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta charset="utf-8">
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css", media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <% if flash.present? %>
      <div class="row">
        <div class="col-md-12">
          <%= flash_messages %>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pets/_geo_search.html.erb
<form method="get" class="form-inline">
  <div class="form-group">
    <div class="form-group">
      <label for="city">Pets within </label>
      <input type="number" class="form-control" id="distance" name="distance" value="<%= @search_form[:distance] %>" placeholder="Distance (km)" min="5" max="100">
      <label> kilometers from </label>
      <select name="distance_from" class="form-control" id="city">
        <option></option>
        <% BIGGEST_CITIES.each do |city| %>
          <option value="<%= city[:name] %>" <% if city[:name] == @search_form[:distance_from] %>selected<% end %>><%= city[:name] %></option>
        <% end %>
      </select>
    </div>
    <div class="form-group">
      <input type="submit" value="Search" class="btn btn-primary">
    </div>
    <%
      random_city = BIGGEST_CITIES.sample[:name]
      random_distance = rand(5..100)
    %>
    <hr />
    <p>Not sure? Perhaps you'd like a pet
      <a href="?distance=<%= random_distance %>&distance_from=<%= random_city %>">
        within <%= random_distance %>km from <%= random_city %>
      </a>
    </p>
  </div>
</form>

app/views/pets/_pet_panel.html.erb
<% PetView.create(pet_id: pet.id) %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to pet.name, pet %></h3>
  </div>
  <div class="panel-body">
    <center>
      <%= image_tag pet.image_url, class: 'img-responsive' %>
      <p><%= pet.description.truncate(50) %></p>
    </center>
  </div>
  <div class="panel-footer">
    Age: <%= pet.age %>
    Views: <%= pet.pet_views.count %>
    <div class="pull-right">
      <div class="btn btn-link btn-sm"><%= link_to 'Show', pet %></div>
    </div>
  </div>
</div>

app/views/pets/_pets_list.html.erb
<% title ||= nil %>
<% filter ||= nil %>
<div class="row">
  <div class="col-md-12">
    <h2><%= title || filter.to_s.humanize %></h2>
  </div>
  <% pets.each do |pet| %>
    <div class="col-md-3">
      <%= render 'pets/pet_panel', pet: pet %>
    </div>
  <% end %>
</div>

app/views/pets/cats.html.erb
<div class="container">
  <%= render 'geo_search' %>
  <% if @search %>
    <div class="row">
      <div class="col-md-12">
        <h1>Search results for "<%= @search %>" with <%= @pets_count %> results</h1>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-md-12">
        <h1>Found <%= pluralize(@pets_count, 'pet') %> matching your search</h1>
      </div>
    </div>
  <% end %>

  <div class="col-md-12">
    <center>
      <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
    </center>
  </div>

  <%= render 'pets/pets_list', pets: @pets.limit(12), filter: @filter %>

  <div class="col-md-12">
    <center>
      <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
    </center>
  </div>
</div>

app/views/pets/dogs.html.erb
<div class="container">
  <%= render 'geo_search' %>
  <% if @search %>
    <div class="row">
      <div class="col-md-12">
        <h1>Search results for "<%= @search %>" with <%= @pets_count %> results</h1>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-md-12">
        <h1>Found <%= pluralize(@pets_count, 'pet') %> matching your search</h1>
      </div>
    </div>
  <% end %>

  <div class="col-md-12">
    <center>
      <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
    </center>
  </div>

  <%= render 'pets/pets_list', pets: @pets.limit(12), filter: @filter %>

  <div class="col-md-12">
    <center>
      <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
    </center>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container">
  <% if @search %>
    <div class="row">
      <div class="col-md-12">
        <h1>Search results for "<%= @search %>" with <%= @pets_count %> results</h1>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-md-12">
        <h1>Found <%= pluralize(@pets_count, 'pet') %> matching your search</h1>
      </div>
    </div>
  <% end %>

  <div class="col-md-12">
    <center>
      <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
    </center>
  </div>

  <%= render 'pets/pets_list', pets: @pets.limit(12), filter: @filter %>

  <div class="col-md-12">
    <center>
      <%= paginate @pets, theme: 'twitter-bootstrap-3' %>
    </center>
  </div>
</div>

app/views/pets/show.html.erb
<% pet ||= @pet %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pet.pet_type.to_s.humanize %></h3>
        </div>
        <div class="panel-body">
          <%= image_tag(pet.image_url(width: 300, height: 300), class: "img-responsive") %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h1><%= pet.name %></h1>
      <p><%= pet.description %></p>
      <p><%= pet.tagline %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3><%= pet.promo %></h3>
      <table class="table">
        <% [
             ['Name', pet.name],
             ['Age', pet.age],
             ['Breed', pet.breed],
             ['Color', pet.color],
             ['Weight', pet.weight],
             ['Pet type', pet.pet_type.to_s.humanize],
             ['Gender', pet.gender.to_s.humanize],
             ['Size', pet.size.to_s.humanize],
             ['Microchip number', pet.microchip_number],
             ['Neutered', pet.neutered],
             ['House trained', pet.house_trained],
             ['Special needs', pet.special_needs],
             ['Suitable for apartments', pet.suitable_for_apartments],
             ['Good with kids', pet.good_with_kids],
             ['Good with other pets', pet.good_with_other_pets],
             ['Activity level', pet.activity_level],
             ['Personality traits', pet.personality_traits],
             ['Medical conditions', pet.medical_conditions],
             ['Allergies', pet.allergies],
             ['Description', pet.description],
             ['Biography', pet.biography],
             ['Date of birth', pet.date_of_birth],
             ['Arrival date', pet.arrival_date],
             ['Adoption date', pet.adoption_date],
             ['Shelter', pet.shelter.name],
             ['Created at', pet.created_at.strftime('%Y-%m-%d %H:%M:%S')],
             ['Updated at', pet.updated_at.strftime('%Y-%m-%d %H:%M:%S')]
           ].each do |label, value| %>
          <tr>
            <th><%= label %></th>
            <td><%= value %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= render 'pets/pets_list', pets: pet.similar_type_pets.limit(4), title: "Similar type pets (#{pet.similar_type_pets.count})" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= render 'pets/pets_list', pets: pet.similiar_name_pets.limit(4), title: "Similiar name pets (#{pet.similiar_name_pets.count})" %>
    </div>
  </div>
</div>